version: '3'

services:
  gobarber-api:
    container_name: gobarber-api
    build: '.'
    entrypoint: ['./init.sh']
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - gobarber-postgres
    networks:
      - app-connect
    ports:
      - '3333:3333'

  gobarber-postgres:
    container_name: gobarber-postgres
    build: './db'
    volumes:
      - gobarber-postgres-data:/data
    environment:
      POSTGRES_DB: gobarber
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      PGPORT: 5432
    networks:
      - app-connect
    ports:
      - '5432:5432'

volumes:
  gobarber-postgres-data:

networks:
  app-connect:
      driver: bridge
